{
 "title": "Smart Meter",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Actual Electrical Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "actual_consumption" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "High Tariff Meter Value",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "consumption_high_tariff" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Low Tariff Meter Value",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "consumption_low_tariff" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actual Electrical Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "actual_consumption" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electrical Meter Value",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "electricity",
     "query": "SELECT (\"consumption_low_tariff\" + \"consumption_high_tariff\")  / 1000 FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "consumption_low_tariff" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actual Gas Consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "gas",
     "query": "SELECT difference(last(\"actual_consumption\"))/1000 FROM \"gas\" WHERE $timeFilter GROUP BY time(8m)\n",
     "select": [
      [
       { "params": [ "actual_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Meter Value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gas",
     "select": [
      [
       { "params": [ "actual_consumption" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electrical Energy Consumption Accumulated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth", "label": "High Tariff" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "consumption_high_tariff" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "High Tariff" ], "type": "alias" }
      ],
      [
       { "params": [ "consumption_low_tariff" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Low Tariff" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electrical Energy Consumption / Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"consumption_high_tariff\") - first(\"consumption_high_tariff\")) as \"High Tariff\" FROM \"electricity\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"consumption_low_tariff\") - first(\"consumption_low_tariff\")) as \"Low Tariff\" FROM \"electricity\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Consumption Accumulated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "measurement": "gas",
     "select": [
      [
       { "params": [ "actual_consumption" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Consumption / Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "gas",
     "query": "SELECT (last(\"actual_consumption\" ) - first(\"actual_consumption\") )/ 1000 FROM \"gas\" WHERE $timeFilter Group by time(1h) ",
     "select": [
      [
       { "params": [ "actual_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electrical Energy Consumption / day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"consumption_high_tariff\") - first(\"consumption_high_tariff\")) as \"High Tariff\" FROM \"electricity\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"consumption_low_tariff\") - first(\"consumption_low_tariff\")) as \"Low Tariff\" FROM \"electricity\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas Consumption / day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "gas",
     "query": "SELECT (last(\"actual_consumption\" ) - first(\"actual_consumption\") )/ 1000 FROM \"gas\" WHERE $timeFilter Group by time(1d) ",
     "select": [
      [
       { "params": [ "actual_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}